### ISSUE TITLE
Documentation on old/new code

### ISSUE THREAD

**Issue by Robert8944** [Robert8944/sqsg6#42]
Reread and write documentation for last years code base.

**Comment by ddilger** [comment]
I think this is applicable to the code that each of us is working on. Dr. P talked a lot about clarifying the database interaction code I worked with. Since Robert will be working on profile.php he can add clarifying comments to that file. I will add comments to the other files that I worked on. Kirk can comment on the display features he introduced.

**Comment by thingscouldbeworse** [comment]
I think it makes sense to roll new code documentation into this issue as well, as that's how we've been treating it. This issue represents commenting code, and is separate from the final documentation deliverable.

**Comment by thingscouldbeworse** [comment]
Closed as the final documentation is written and sent
